#!/bin/bash
set -e

mariadb -u root -p${MARIADB_ROOT_PASSWORD} <<-EOSQL
	CREATE DATABASE IF NOT EXISTS \`${WP_SQL_DATABASE}\`;

	CREATE USER IF NOT EXISTS '${WP_SQL_USER}'@'%' IDENTIFIED BY '${WP_SQL_PASSWORD}';

	GRANT ALL PRIVILEGES ON \`${WP_SQL_DATABASE}\`.* TO '${WP_SQL_USER}'@'%';

	FLUSH PRIVILEGES;
EOSQL
