CREATE DATABASE IF NOT EXISTS ${WP_SQL_DATABASE};

CREATE USER IF NOT EXISTS '${WP_SQL_USER}'@'wordpress.cloud1' IDENTIFIED BY '${WP_SQL_PASSWORD}';

GRANT ALL PRIVILEGES ON ${WP_SQL_DATABASE}.* TO '${WP_SQL_USER}'@'wordpress.cloud1';

ALTER USER 'root'@'localhost' IDENTIFIED BY '${SQL_ROOT_PASSWORD}';

FLUSH PRIVILEGES;